apiVersion: v1
kind: Service
metadata:
  name: {{ template "pion.fullname" . }}-manager
  labels:
    app: {{ template "pion.name" . }}
    component: manager
    chart: {{ template "pion.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "pion.name" . }}
    component: manager
    release: {{ .Release.Name }}
